filter:
  queue: URANUS.CSC.FLIGHT
  callsign-prefix-restriction: CSC

server:
  port: 9002
spring:
  activemq:
    in-memory: false
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: false
      max-connections: 100
  jms:
    pub-sub-domain: true
  rabbitmq:
    host: fusion-mq.dizall.com
    username: admin
    password: Mf#llsy78g
    port: 5672
  cloud:
    stream:
      bindings:
        flight-input:
          destination: uranus.fusion
          group: cscFlight
          content-type: application/json
      rabbit:
        bindings:
          flight-input:
            consumer:
              binding-routing-key: indraFlightTrack
