server:
  port: 9000

uranus:
  udp:
    multicast:
      splitter:
        inbound:
          local-address: 192.168.0.12
          group: 225.25.25.25
          port: 50000
        outbounds:
          - ip: 192.168.0.12
            port: 20000
            enabled: true
          - ip: 192.168.0.12
            port: 20001
            enabled: true
          - ip: 192.168.0.12
            port: 20002
            enabled: false
